### ISSUE TITLE
Implement loading functions from static linked libraries

### ISSUE THREAD

**Issue by playXE** [playXE/PeakJIT#1]
Example:
```rust
let func = Function::new(Name::External("printf");
```

**Comment by Nopey** [comment]
It sounds like you want to resolve a symbol at runtime, which is exactly what `ld-linux.so` does for linux, and windows api provides. Statically linked libraries are traditionally linked at compile time, and may not be available on the end-user's machine. (If it is linked at compile time, the symbols are often stripped)

This seems out of this project's scope, but could be a fairly simple crate.

If you want to search all loaded dynamic libs:
```rust
let func = Function::new(dynsym::load_sym("printf", dynsym::Search));
//on linux, maps pretty much to
   let func = Function::new(dlsym("printf", RTLD_DEFAULT))
//on windows, we emulate RTLD_DEFAULT by feeding the modules returned from EnumProcessModules through GetProcAddress, until we find "printf"
```
Or, if you know what library contains printf:
```rust
// LoadLibrary("msvcrt.dll") on win, dlopen("libc.so") on nix
let libc = dynsym::load_libc();
// GetProcAddress("printf", libc) on win, dlsym("printf", libc) on nix
let func = Function::new(dynsym::load_sym("printf", libc));
```

**Comment by playXE** [comment]
@Nopey thank you for your help!
